# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-04-19 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0010_auto_20250419_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyroom',
            name='room_capacity',
            field=models.IntegerField(help_text='Maximum number of students allowed'),
        ),
    ]
