# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-04-19 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0011_auto_20250419_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalResource',
            fields=[
                ('resource_number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('MAGAZINE', 'Magazine'), ('JOURNAL', 'Journal'), ('BOOK', 'Book'), ('RESEARCH', 'Research Paper')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='digital_resources/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='digital_resources/covers/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
