# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-04-19 14:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libapp', '0013_auto_20250419_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedbookrequest',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libapp.Book'),
        ),
        migrations.AddField(
            model_name='acceptedbookrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='acceptedbookrequest',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libapp.BookRequest'),
        ),
    ]
