# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-04-19 15:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libapp', '0014_auto_20250419_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalEngagementRecord',
            fields=[
                ('download_date', models.DateTimeField(auto_now_add=True)),
                ('download_number', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.DigitalResource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Digital Engagement Record',
                'verbose_name_plural': 'Digital Engagement Records',
                'ordering': ['-download_date'],
            },
        ),
    ]
