# Generated by Django 3.2 on 2025-04-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0016_auto_20250420_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
